# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/inmuebles_db
spring.datasource.username=postgres
spring.datasource.password=oAGCLv.*2024
spring.datasource.driver-class-name=org.postgresql.Driver

# Crea o actualiza las tablas automáticamente basándose en tu modelo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true